#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "-i" "$@")

[[ -n $password ]] || exit

## TODO DETERMINE WHETHER pass-otp IS INSTALLED

# Determine whether the password is an OTP code or not
echo "Determining whether the password is an OTP code"
pass show "$password" | grep "otpauth://" 2>/dev/null && otp=1

if [[ $typeit -eq 0 ]]; then
	[[ $otp -eq 1 ]] && pass otp -c "$password" 2>/dev/null ||
		pass show -c "$password" 2>/dev/null
else
	if [[ $otp -eq 1 ]]; then
		pass otp "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
	else
		pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
	fi
fi
