#!/bin/sh
BASEURL="https://www.youtube.com/feeds/videos.xml?channel_id="

# Invidious Instances
# BASEURL="https://vid.puffyan.us/feed/channel/"
# BASEURL="https://invidious.snopyta.org/feed/channel/"
# BASEURL="https://invidious.kavin.rocks/feed/channel/"
# BASEURL="https://inv.riverside.rocks/feed/channel/"

[ -z "$1" ]  && printf "Usage: yt-id [options] -u [URL | Username]\n" && exit 0

URL=$1
curl -Ls "$URL" > /dev/null || URL="https://www.youtube.com/$URL"

# Actually getting the ID
read ID < <(curl -Ls "$URL" | grep -o -P '.{0,0}channel_id.{0,25}' | sed '$!d' | cut -c 12-35)
[ -z "$ID" ] && printf "Channel not found.\n" && exit 1

# Prints out the credentials
printf "ID:\t%s\n" $ID
printf "RSS:\t%s\n" $BASEURL$ID
